export const equipos = [
  {
    id: 1,
    nombre: "Real Madrid 2002",
    liga: "La Liga",
    pais: "España",
    temporada: "2001/02",
    escudo: "🏆",
    media: 87,
    jugadores: [
      { id: 101, nombre: "Casillas", posicion: "POR", valoracion: 87, jugador_real_id: 1 },
      { id: 102, nombre: "Salgado", posicion: "LD", valoracion: 79, jugador_real_id: 2 },
      { id: 103, nombre: "Hierro", posicion: "DFC", valoracion: 85, jugador_real_id: 3 },
      { id: 104, nombre: "Helguera", posicion: "DFC", valoracion: 79, jugador_real_id: 4 },
      { id: 105, nombre: "Roberto Carlos", posicion: "LI", valoracion: 90, jugador_real_id: 5 },
      { id: 106, nombre: "Makelele", posicion: "MCD", valoracion: 87, jugador_real_id: 6 },
      { id: 107, nombre: "Zidane", posicion: "MC", valoracion: 95, jugador_real_id: 7 },
      { id: 108, nombre: "Figo", posicion: "MD", valoracion: 92, jugador_real_id: 8 },
      { id: 109, nombre: "McManaman", posicion: "MI", valoracion: 78, jugador_real_id: 9 },
      { id: 110, nombre: "Ronaldo", posicion: "DC", valoracion: 94, jugador_real_id: 10 },
      { id: 111, nombre: "Morientes", posicion: "DC", valoracion: 83, jugador_real_id: 11 },
      { id: 112, nombre: "Raúl", posicion: "DC", valoracion: 89, jugador_real_id: 12 },
      { id: 113, nombre: "Flavio Conceicao", posicion: "MC", valoracion: 76, jugador_real_id: 13 },
      { id: 114, nombre: "Solari", posicion: "MI", valoracion: 77, jugador_real_id: 14 },
      { id: 115, nombre: "Cambiasso", posicion: "MCD", valoracion: 78, jugador_real_id: 15 }
    ]
  },
  {
    id: 2,
    nombre: "Barcelona 2009",
    liga: "La Liga",
    pais: "España",
    temporada: "2008/09",
    escudo: "🏆",
    media: 89,
    jugadores: [
      { id: 201, nombre: "Valdés", posicion: "POR", valoracion: 85, jugador_real_id: 16 },
      { id: 202, nombre: "Alves", posicion: "LD", valoracion: 87, jugador_real_id: 17 },
      { id: 203, nombre: "Piqué", posicion: "DFC", valoracion: 83, jugador_real_id: 18 },
      { id: 204, nombre: "Puyol", posicion: "DFC", valoracion: 87, jugador_real_id: 19 },
      { id: 205, nombre: "Abidal", posicion: "LI", valoracion: 84, jugador_real_id: 20 },
      { id: 206, nombre: "Busquets", posicion: "MCD", valoracion: 82, jugador_real_id: 21 },
      { id: 207, nombre: "Xavi", posicion: "MC", valoracion: 93, jugador_real_id: 22 },
      { id: 208, nombre: "Iniesta", posicion: "MC", valoracion: 92, jugador_real_id: 23 },
      { id: 209, nombre: "Henry", posicion: "EI", valoracion: 87, jugador_real_id: 24 },
      { id: 210, nombre: "Messi", posicion: "SD", valoracion: 94, jugador_real_id: 25 },
      { id: 211, nombre: "Eto'o", posicion: "DC", valoracion: 90, jugador_real_id: 26 },
      { id: 212, nombre: "Keita", posicion: "MC", valoracion: 79, jugador_real_id: 27 },
      { id: 213, nombre: "Sylvinho", posicion: "LI", valoracion: 76, jugador_real_id: 28 },
      { id: 214, nombre: "Touré Yaya", posicion: "MCD", valoracion: 84, jugador_real_id: 29 },
      { id: 215, nombre: "Gudjohnsen", posicion: "DC", valoracion: 77, jugador_real_id: 30 }
    ]
  },
  {
    id: 3,
    nombre: "Milan 2007",
    liga: "Serie A",
    pais: "Italia",
    temporada: "2006/07",
    escudo: "🏆",
    media: 85,
    jugadores: [
      { id: 301, nombre: "Dida", posicion: "POR", valoracion: 85, jugador_real_id: 31 },
      { id: 302, nombre: "Oddo", posicion: "LD", valoracion: 78, jugador_real_id: 32 },
      { id: 303, nombre: "Nesta", posicion: "DFC", valoracion: 89, jugador_real_id: 33 },
      { id: 304, nombre: "Maldini", posicion: "DFC", valoracion: 86, jugador_real_id: 34 },
      { id: 305, nombre: "Jankulovski", posicion: "LI", valoracion: 78, jugador_real_id: 35 },
      { id: 306, nombre: "Gattuso", posicion: "MCD", valoracion: 83, jugador_real_id: 36 },
      { id: 307, nombre: "Pirlo", posicion: "MCD", valoracion: 89, jugador_real_id: 37 },
      { id: 308, nombre: "Seedorf", posicion: "MC", valoracion: 85, jugador_real_id: 38 },
      { id: 309, nombre: "Kaká", posicion: "SD", valoracion: 93, jugador_real_id: 39 },
      { id: 310, nombre: "Inzaghi", posicion: "DC", valoracion: 83, jugador_real_id: 40 },
      { id: 311, nombre: "Gilardino", posicion: "DC", valoracion: 81, jugador_real_id: 41 },
      { id: 312, nombre: "Ambrosini", posicion: "MC", valoracion: 78, jugador_real_id: 42 },
      { id: 313, nombre: "Cafu", posicion: "LD", valoracion: 82, jugador_real_id: 43 },
      { id: 314, nombre: "Shevchenko", posicion: "DC", valoracion: 88, jugador_real_id: 44 },
      { id: 315, nombre: "Vogel", posicion: "MCD", valoracion: 76, jugador_real_id: 45 }
    ]
  },
  {
    id: 4,
    nombre: "Manchester United 1999",
    liga: "Premier League",
    pais: "Inglaterra",
    temporada: "1998/99",
    escudo: "🏆",
    media: 85,
    jugadores: [
      { id: 401, nombre: "Schmeichel", posicion: "POR", valoracion: 91, jugador_real_id: 46 },
      { id: 402, nombre: "Gary Neville", posicion: "LD", valoracion: 82, jugador_real_id: 47 },
      { id: 403, nombre: "Stam", posicion: "DFC", valoracion: 88, jugador_real_id: 48 },
      { id: 404, nombre: "Johnsen", posicion: "DFC", valoracion: 78, jugador_real_id: 49 },
      { id: 405, nombre: "Irwin", posicion: "LI", valoracion: 82, jugador_real_id: 50 },
      { id: 406, nombre: "Beckham", posicion: "MD", valoracion: 87, jugador_real_id: 51 },
      { id: 407, nombre: "Keane", posicion: "MCD", valoracion: 91, jugador_real_id: 52 },
      { id: 408, nombre: "Scholes", posicion: "MC", valoracion: 87, jugador_real_id: 53 },
      { id: 409, nombre: "Giggs", posicion: "MI", valoracion: 88, jugador_real_id: 54 },
      { id: 410, nombre: "Yorke", posicion: "DC", valoracion: 86, jugador_real_id: 55 },
      { id: 411, nombre: "Cole", posicion: "DC", valoracion: 85, jugador_real_id: 56 },
      { id: 412, nombre: "Sheringham", posicion: "DC", valoracion: 81, jugador_real_id: 57 },
      { id: 413, nombre: "Solskjaer", posicion: "DC", valoracion: 80, jugador_real_id: 58 },
      { id: 414, nombre: "P. Neville", posicion: "MCD", valoracion: 76, jugador_real_id: 59 },
      { id: 415, nombre: "Blomqvist", posicion: "MI", valoracion: 74, jugador_real_id: 60 }
    ]
  },
  {
    id: 5,
    nombre: "Bayern Munich 2013",
    liga: "Bundesliga",
    pais: "Alemania",
    temporada: "2012/13",
    escudo: "🏆",
    media: 87,
    jugadores: [
      { id: 501, nombre: "Neuer", posicion: "POR", valoracion: 92, jugador_real_id: 61 },
      { id: 502, nombre: "Lahm", posicion: "LD", valoracion: 90, jugador_real_id: 62 },
      { id: 503, nombre: "Boateng", posicion: "DFC", valoracion: 86, jugador_real_id: 63 },
      { id: 504, nombre: "Dante", posicion: "DFC", valoracion: 81, jugador_real_id: 64 },
      { id: 505, nombre: "Alaba", posicion: "LI", valoracion: 84, jugador_real_id: 65 },
      { id: 506, nombre: "Schweinsteiger", posicion: "MCD", valoracion: 88, jugador_real_id: 66 },
      { id: 507, nombre: "Martínez", posicion: "MCD", valoracion: 84, jugador_real_id: 67 },
      { id: 508, nombre: "Müller", posicion: "MC", valoracion: 87, jugador_real_id: 68 },
      { id: 509, nombre: "Robben", posicion: "ED", valoracion: 89, jugador_real_id: 69 },
      { id: 510, nombre: "Ribéry", posicion: "EI", valoracion: 90, jugador_real_id: 70 },
      { id: 511, nombre: "Mandžukić", posicion: "DC", valoracion: 83, jugador_real_id: 71 },
      { id: 512, nombre: "Gomez", posicion: "DC", valoracion: 84, jugador_real_id: 72 },
      { id: 513, nombre: "Van Buyten", posicion: "DFC", valoracion: 79, jugador_real_id: 73 },
      { id: 514, nombre: "Kroos", posicion: "MC", valoracion: 86, jugador_real_id: 74 },
      { id: 515, nombre: "Rafinha", posicion: "LD", valoracion: 76, jugador_real_id: 75 }
    ]
  },
  {
    id: 6,
    nombre: "Barcelona 2011",
    liga: "La Liga",
    pais: "España",
    temporada: "2010/11",
    escudo: "🏆",
    media: 90,
    jugadores: [
      { id: 601, nombre: "Valdés", posicion: "POR", valoracion: 86, jugador_real_id: 16 },
      { id: 602, nombre: "Alves", posicion: "LD", valoracion: 88, jugador_real_id: 17 },
      { id: 603, nombre: "Piqué", posicion: "DFC", valoracion: 86, jugador_real_id: 18 },
      { id: 604, nombre: "Puyol", posicion: "DFC", valoracion: 86, jugador_real_id: 19 },
      { id: 605, nombre: "Abidal", posicion: "LI", valoracion: 83, jugador_real_id: 20 },
      { id: 606, nombre: "Busquets", posicion: "MCD", valoracion: 86, jugador_real_id: 21 },
      { id: 607, nombre: "Xavi", posicion: "MC", valoracion: 94, jugador_real_id: 22 },
      { id: 608, nombre: "Iniesta", posicion: "MC", valoracion: 93, jugador_real_id: 23 },
      { id: 609, nombre: "Pedro", posicion: "EI", valoracion: 83, jugador_real_id: 76 },
      { id: 610, nombre: "Messi", posicion: "SD", valoracion: 96, jugador_real_id: 25 },
      { id: 611, nombre: "Villa", posicion: "DC", valoracion: 89, jugador_real_id: 77 },
      { id: 612, nombre: "Keita", posicion: "MC", valoracion: 79, jugador_real_id: 27 },
      { id: 613, nombre: "Maxwell", posicion: "LI", valoracion: 77, jugador_real_id: 78 },
      { id: 614, nombre: "Touré Yaya", posicion: "MCD", valoracion: 85, jugador_real_id: 29 },
      { id: 615, nombre: "Adriano", posicion: "LI", valoracion: 78, jugador_real_id: 79 }
    ]
  },
  {
    id: 7,
    nombre: "Real Madrid 2014",
    liga: "La Liga",
    pais: "España",
    temporada: "2013/14",
    escudo: "🏆",
    media: 88,
    jugadores: [
      { id: 701, nombre: "Casillas", posicion: "POR", valoracion: 87, jugador_real_id: 1 },
      { id: 702, nombre: "Carvajal", posicion: "LD", valoracion: 82, jugador_real_id: 80 },
      { id: 703, nombre: "Varane", posicion: "DFC", valoracion: 84, jugador_real_id: 81 },
      { id: 704, nombre: "Ramos", posicion: "DFC", valoracion: 89, jugador_real_id: 82 },
      { id: 705, nombre: "Marcelo", posicion: "LI", valoracion: 87, jugador_real_id: 83 },
      { id: 706, nombre: "Khedira", posicion: "MCD", valoracion: 84, jugador_real_id: 84 },
      { id: 707, nombre: "Modric", posicion: "MC", valoracion: 90, jugador_real_id: 85 },
      { id: 708, nombre: "Di María", posicion: "EI", valoracion: 88, jugador_real_id: 86 },
      { id: 709, nombre: "Bale", posicion: "ED", valoracion: 89, jugador_real_id: 87 },
      { id: 710, nombre: "Benzema", posicion: "DC", valoracion: 87, jugador_real_id: 88 },
      { id: 711, nombre: "Ronaldo", posicion: "EI", valoracion: 96, jugador_real_id: 89 },
      { id: 712, nombre: "Xabi Alonso", posicion: "MCD", valoracion: 88, jugador_real_id: 90 },
      { id: 713, nombre: "Isco", posicion: "MC", valoracion: 82, jugador_real_id: 91 },
      { id: 714, nombre: "Coentrao", posicion: "LI", valoracion: 81, jugador_real_id: 92 },
      { id: 715, nombre: "Pepe", posicion: "DFC", valoracion: 85, jugador_real_id: 93 }
    ]
  },
  {
    id: 8,
    nombre: "Real Madrid 2018",
    liga: "La Liga",
    pais: "España",
    temporada: "2017/18",
    escudo: "🏆",
    media: 88,
    jugadores: [
      { id: 801, nombre: "Navas", posicion: "POR", valoracion: 88, jugador_real_id: 94 },
      { id: 802, nombre: "Carvajal", posicion: "LD", valoracion: 85, jugador_real_id: 80 },
      { id: 803, nombre: "Varane", posicion: "DFC", valoracion: 88, jugador_real_id: 81 },
      { id: 804, nombre: "Ramos", posicion: "DFC", valoracion: 91, jugador_real_id: 82 },
      { id: 805, nombre: "Marcelo", posicion: "LI", valoracion: 88, jugador_real_id: 83 },
      { id: 806, nombre: "Casemiro", posicion: "MCD", valoracion: 87, jugador_real_id: 95 },
      { id: 807, nombre: "Modric", posicion: "MC", valoracion: 92, jugador_real_id: 85 },
      { id: 808, nombre: "Kroos", posicion: "MC", valoracion: 91, jugador_real_id: 74 },
      { id: 809, nombre: "Isco", posicion: "MC", valoracion: 87, jugador_real_id: 91 },
      { id: 810, nombre: "Benzema", posicion: "DC", valoracion: 88, jugador_real_id: 88 },
      { id: 811, nombre: "Ronaldo", posicion: "EI", valoracion: 97, jugador_real_id: 89 },
      { id: 812, nombre: "Bale", posicion: "ED", valoracion: 88, jugador_real_id: 87 },
      { id: 813, nombre: "Asensio", posicion: "ED", valoracion: 83, jugador_real_id: 96 },
      { id: 814, nombre: "Lucas Vázquez", posicion: "ED", valoracion: 79, jugador_real_id: 97 },
      { id: 815, nombre: "Kovacic", posicion: "MC", valoracion: 83, jugador_real_id: 98 }
    ]
  },
  {
    id: 9,
    nombre: "Liverpool 2019",
    liga: "Premier League",
    pais: "Inglaterra",
    temporada: "2018/19",
    escudo: "🏆",
    media: 87,
    jugadores: [
      { id: 901, nombre: "Alisson", posicion: "POR", valoracion: 89, jugador_real_id: 99 },
      { id: 902, nombre: "Alexander-Arnold", posicion: "LD", valoracion: 84, jugador_real_id: 100 },
      { id: 903, nombre: "Matip", posicion: "DFC", valoracion: 82, jugador_real_id: 101 },
      { id: 904, nombre: "Van Dijk", posicion: "DFC", valoracion: 91, jugador_real_id: 102 },
      { id: 905, nombre: "Robertson", posicion: "LI", valoracion: 86, jugador_real_id: 103 },
      { id: 906, nombre: "Fabinho", posicion: "MCD", valoracion: 86, jugador_real_id: 104 },
      { id: 907, nombre: "Henderson", posicion: "MC", valoracion: 83, jugador_real_id: 105 },
      { id: 908, nombre: "Wijnaldum", posicion: "MC", valoracion: 83, jugador_real_id: 106 },
      { id: 909, nombre: "Salah", posicion: "ED", valoracion: 91, jugador_real_id: 107 },
      { id: 910, nombre: "Firmino", posicion: "DC", valoracion: 86, jugador_real_id: 108 },
      { id: 911, nombre: "Mané", posicion: "EI", valoracion: 89, jugador_real_id: 109 },
      { id: 912, nombre: "Milner", posicion: "MC", valoracion: 80, jugador_real_id: 110 },
      { id: 913, nombre: "Origi", posicion: "DC", valoracion: 76, jugador_real_id: 111 },
      { id: 914, nombre: "Keita", posicion: "MC", valoracion: 80, jugador_real_id: 112 },
      { id: 915, nombre: "Shaqiri", posicion: "ED", valoracion: 79, jugador_real_id: 113 }
    ]
  },
  {
    id: 10,
    nombre: "Porto 2004",
    liga: "Primeira Liga",
    pais: "Portugal",
    temporada: "2003/04",
    escudo: "🏆",
    media: 78,
    jugadores: [
      { id: 1001, nombre: "Vítor Baía", posicion: "POR", valoracion: 82, jugador_real_id: 114 },
      { id: 1002, nombre: "Paulo Ferreira", posicion: "LD", valoracion: 77, jugador_real_id: 115 },
      { id: 1003, nombre: "Jorge Costa", posicion: "DFC", valoracion: 76, jugador_real_id: 116 },
      { id: 1004, nombre: "Ricardo Carvalho", posicion: "DFC", valoracion: 82, jugador_real_id: 117 },
      { id: 1005, nombre: "Nuno Valente", posicion: "LI", valoracion: 76, jugador_real_id: 118 },
      { id: 1006, nombre: "Costinha", posicion: "MCD", valoracion: 76, jugador_real_id: 119 },
      { id: 1007, nombre: "Maniche", posicion: "MC", valoracion: 80, jugador_real_id: 120 },
      { id: 1008, nombre: "Deco", posicion: "SD", valoracion: 85, jugador_real_id: 121 },
      { id: 1009, nombre: "Quaresma", posicion: "ED", valoracion: 78, jugador_real_id: 122 },
      { id: 1010, nombre: "Derlei", posicion: "DC", valoracion: 74, jugador_real_id: 123 },
      { id: 1011, nombre: "McCarthy", posicion: "DC", valoracion: 75, jugador_real_id: 124 },
      { id: 1012, nombre: "Pedro Emanuel", posicion: "MCD", valoracion: 74, jugador_real_id: 125 },
      { id: 1013, nombre: "Alenitchev", posicion: "MC", valoracion: 77, jugador_real_id: 126 },
      { id: 1014, nombre: "Postiga", posicion: "DC", valoracion: 74, jugador_real_id: 127 },
      { id: 1015, nombre: "Nuno Frechaut", posicion: "DFC", valoracion: 72, jugador_real_id: 128 }
    ]
  },
  {
    id: 11,
    nombre: "Chelsea 2012",
    liga: "Premier League",
    pais: "Inglaterra",
    temporada: "2011/12",
    escudo: "🏆",
    media: 84,
    jugadores: [
      { id: 1101, nombre: "Cech", posicion: "POR", valoracion: 89, jugador_real_id: 129 },
      { id: 1102, nombre: "Bosingwa", posicion: "LD", valoracion: 78, jugador_real_id: 130 },
      { id: 1103, nombre: "Terry", posicion: "DFC", valoracion: 87, jugador_real_id: 131 },
      { id: 1104, nombre: "Cahill", posicion: "DFC", valoracion: 82, jugador_real_id: 132 },
      { id: 1105, nombre: "Cole", posicion: "LI", valoracion: 87, jugador_real_id: 133 },
      { id: 1106, nombre: "Mikel", posicion: "MCD", valoracion: 77, jugador_real_id: 134 },
      { id: 1107, nombre: "Lampard", posicion: "MC", valoracion: 88, jugador_real_id: 135 },
      { id: 1108, nombre: "Ramires", posicion: "MC", valoracion: 80, jugador_real_id: 136 },
      { id: 1109, nombre: "Mata", posicion: "SD", valoracion: 86, jugador_real_id: 137 },
      { id: 1110, nombre: "Drogba", posicion: "DC", valoracion: 90, jugador_real_id: 138 },
      { id: 1111, nombre: "Kalou", posicion: "ED", valoracion: 77, jugador_real_id: 139 },
      { id: 1112, nombre: "Meireles", posicion: "MC", valoracion: 79, jugador_real_id: 140 },
      { id: 1113, nombre: "Sturridge", posicion: "DC", valoracion: 78, jugador_real_id: 141 },
      { id: 1114, nombre: "Torres", posicion: "DC", valoracion: 83, jugador_real_id: 142 },
      { id: 1115, nombre: "Bertrand", posicion: "LI", valoracion: 74, jugador_real_id: 143 }
    ]
  },
  {
    id: 12,
    nombre: "Inter Milan 2010",
    liga: "Serie A",
    pais: "Italia",
    temporada: "2009/10",
    escudo: "🏆",
    media: 85,
    jugadores: [
      { id: 1201, nombre: "Julio César", posicion: "POR", valoracion: 87, jugador_real_id: 144 },
      { id: 1202, nombre: "Maicon", posicion: "LD", valoracion: 88, jugador_real_id: 145 },
      { id: 1203, nombre: "Lucio", posicion: "DFC", valoracion: 85, jugador_real_id: 146 },
      { id: 1204, nombre: "Samuel", posicion: "DFC", valoracion: 83, jugador_real_id: 147 },
      { id: 1205, nombre: "Zanetti", posicion: "LI", valoracion: 84, jugador_real_id: 148 },
      { id: 1206, nombre: "Cambiasso", posicion: "MCD", valoracion: 85, jugador_real_id: 15 },
      { id: 1207, nombre: "Motta", posicion: "MCD", valoracion: 81, jugador_real_id: 149 },
      { id: 1208, nombre: "Sneijder", posicion: "SD", valoracion: 90, jugador_real_id: 150 },
      { id: 1209, nombre: "Stankovic", posicion: "MC", valoracion: 80, jugador_real_id: 151 },
      { id: 1210, nombre: "Milito", posicion: "DC", valoracion: 86, jugador_real_id: 152 },
      { id: 1211, nombre: "Eto'o", posicion: "DC", valoracion: 88, jugador_real_id: 26 },
      { id: 1212, nombre: "Pandev", posicion: "EI", valoracion: 78, jugador_real_id: 153 },
      { id: 1213, nombre: "Muntari", posicion: "MC", valoracion: 77, jugador_real_id: 154 },
      { id: 1214, nombre: "Balotelli", posicion: "DC", valoracion: 79, jugador_real_id: 155 },
      { id: 1215, nombre: "Chivu", posicion: "LI", valoracion: 78, jugador_real_id: 156 }
    ]
  },
  {
    id: 13,
    nombre: "Barcelona 2015",
    liga: "La Liga",
    pais: "España",
    temporada: "2014/15",
    escudo: "🏆",
    media: 90,
    jugadores: [
      { id: 1301, nombre: "Ter Stegen", posicion: "POR", valoracion: 84, jugador_real_id: 157 },
      { id: 1302, nombre: "Alves", posicion: "LD", valoracion: 86, jugador_real_id: 17 },
      { id: 1303, nombre: "Piqué", posicion: "DFC", valoracion: 87, jugador_real_id: 18 },
      { id: 1304, nombre: "Mathieu", posicion: "DFC", valoracion: 80, jugador_real_id: 158 },
      { id: 1305, nombre: "Alba", posicion: "LI", valoracion: 86, jugador_real_id: 159 },
      { id: 1306, nombre: "Busquets", posicion: "MCD", valoracion: 89, jugador_real_id: 21 },
      { id: 1307, nombre: "Xavi", posicion: "MC", valoracion: 90, jugador_real_id: 22 },
      { id: 1308, nombre: "Iniesta", posicion: "MC", valoracion: 92, jugador_real_id: 23 },
      { id: 1309, nombre: "Neymar", posicion: "EI", valoracion: 92, jugador_real_id: 160 },
      { id: 1310, nombre: "Messi", posicion: "SD", valoracion: 97, jugador_real_id: 25 },
      { id: 1311, nombre: "Suárez", posicion: "DC", valoracion: 93, jugador_real_id: 161 },
      { id: 1312, nombre: "Rakitic", posicion: "MC", valoracion: 85, jugador_real_id: 162 },
      { id: 1313, nombre: "Mascherano", posicion: "DFC", valoracion: 85, jugador_real_id: 163 },
      { id: 1314, nombre: "Pedro", posicion: "ED", valoracion: 82, jugador_real_id: 76 },
      { id: 1315, nombre: "Adriano", posicion: "LI", valoracion: 77, jugador_real_id: 79 }
    ]
  },
  {
    id: 14,
    nombre: "Real Madrid 2016",
    liga: "La Liga",
    pais: "España",
    temporada: "2015/16",
    escudo: "🏆",
    media: 87,
    jugadores: [
      { id: 1401, nombre: "Navas", posicion: "POR", valoracion: 86, jugador_real_id: 94 },
      { id: 1402, nombre: "Carvajal", posicion: "LD", valoracion: 84, jugador_real_id: 80 },
      { id: 1403, nombre: "Varane", posicion: "DFC", valoracion: 86, jugador_real_id: 81 },
      { id: 1404, nombre: "Ramos", posicion: "DFC", valoracion: 90, jugador_real_id: 82 },
      { id: 1405, nombre: "Marcelo", posicion: "LI", valoracion: 87, jugador_real_id: 83 },
      { id: 1406, nombre: "Casemiro", posicion: "MCD", valoracion: 84, jugador_real_id: 95 },
      { id: 1407, nombre: "Modric", posicion: "MC", valoracion: 91, jugador_real_id: 85 },
      { id: 1408, nombre: "Kroos", posicion: "MC", valoracion: 90, jugador_real_id: 74 },
      { id: 1409, nombre: "Bale", posicion: "ED", valoracion: 90, jugador_real_id: 87 },
      { id: 1410, nombre: "Benzema", posicion: "DC", valoracion: 87, jugador_real_id: 88 },
      { id: 1411, nombre: "Ronaldo", posicion: "EI", valoracion: 96, jugador_real_id: 89 },
      { id: 1412, nombre: "James", posicion: "MC", valoracion: 85, jugador_real_id: 164 },
      { id: 1413, nombre: "Isco", posicion: "MC", valoracion: 84, jugador_real_id: 91 },
      { id: 1414, nombre: "Pepe", posicion: "DFC", valoracion: 84, jugador_real_id: 93 },
      { id: 1415, nombre: "Danilo", posicion: "LD", valoracion: 78, jugador_real_id: 165 }
    ]
  },
  {
    id: 15,
    nombre: "Real Madrid 2017",
    liga: "La Liga",
    pais: "España",
    temporada: "2016/17",
    escudo: "🏆",
    media: 88,
    jugadores: [
      { id: 1501, nombre: "Navas", posicion: "POR", valoracion: 87, jugador_real_id: 94 },
      { id: 1502, nombre: "Carvajal", posicion: "LD", valoracion: 85, jugador_real_id: 80 },
      { id: 1503, nombre: "Varane", posicion: "DFC", valoracion: 87, jugador_real_id: 81 },
      { id: 1504, nombre: "Ramos", posicion: "DFC", valoracion: 91, jugador_real_id: 82 },
      { id: 1505, nombre: "Marcelo", posicion: "LI", valoracion: 88, jugador_real_id: 83 },
      { id: 1506, nombre: "Casemiro", posicion: "MCD", valoracion: 86, jugador_real_id: 95 },
      { id: 1507, nombre: "Modric", posicion: "MC", valoracion: 91, jugador_real_id: 85 },
      { id: 1508, nombre: "Kroos", posicion: "MC", valoracion: 91, jugador_real_id: 74 },
      { id: 1509, nombre: "Isco", posicion: "MC", valoracion: 86, jugador_real_id: 91 },
      { id: 1510, nombre: "Benzema", posicion: "DC", valoracion: 87, jugador_real_id: 88 },
      { id: 1511, nombre: "Ronaldo", posicion: "EI", valoracion: 97, jugador_real_id: 89 },
      { id: 1512, nombre: "Bale", posicion: "ED", valoracion: 89, jugador_real_id: 87 },
      { id: 1513, nombre: "Asensio", posicion: "ED", valoracion: 81, jugador_real_id: 96 },
      { id: 1514, nombre: "Morata", posicion: "DC", valoracion: 82, jugador_real_id: 166 },
      { id: 1515, nombre: "Lucas Vázquez", posicion: "ED", valoracion: 78, jugador_real_id: 97 }
    ]
  },
  {
    id: 16,
    nombre: "Manchester United 2008",
    liga: "Premier League",
    pais: "Inglaterra",
    temporada: "2007/08",
    escudo: "🏆",
    media: 86,
    jugadores: [
      { id: 1601, nombre: "Van der Sar", posicion: "POR", valoracion: 88, jugador_real_id: 167 },
      { id: 1602, nombre: "Brown", posicion: "LD", valoracion: 77, jugador_real_id: 168 },
      { id: 1603, nombre: "Ferdinand", posicion: "DFC", valoracion: 89, jugador_real_id: 169 },
      { id: 1604, nombre: "Vidic", posicion: "DFC", valoracion: 87, jugador_real_id: 170 },
      { id: 1605, nombre: "Evra", posicion: "LI", valoracion: 84, jugador_real_id: 171 },
      { id: 1606, nombre: "Hargreaves", posicion: "MCD", valoracion: 79, jugador_real_id: 172 },
      { id: 1607, nombre: "Carrick", posicion: "MCD", valoracion: 81, jugador_real_id: 173 },
      { id: 1608, nombre: "Scholes", posicion: "MC", valoracion: 87, jugador_real_id: 53 },
      { id: 1609, nombre: "Ronaldo", posicion: "ED", valoracion: 93, jugador_real_id: 89 },
      { id: 1610, nombre: "Rooney", posicion: "DC", valoracion: 88, jugador_real_id: 174 },
      { id: 1611, nombre: "Tevez", posicion: "DC", valoracion: 86, jugador_real_id: 175 },
      { id: 1612, nombre: "Giggs", posicion: "MI", valoracion: 83, jugador_real_id: 54 },
      { id: 1613, nombre: "Nani", posicion: "ED", valoracion: 79, jugador_real_id: 176 },
      { id: 1614, nombre: "Anderson", posicion: "MC", valoracion: 77, jugador_real_id: 177 },
      { id: 1615, nombre: "Saha", posicion: "DC", valoracion: 78, jugador_real_id: 178 }
    ]
  },
  {
    id: 17,
    nombre: "Bayern Munich 2001",
    liga: "Bundesliga",
    pais: "Alemania",
    temporada: "2000/01",
    escudo: "🏆",
    media: 83,
    jugadores: [
      { id: 1701, nombre: "Kahn", posicion: "POR", valoracion: 92, jugador_real_id: 179 },
      { id: 1702, nombre: "Sagnol", posicion: "LD", valoracion: 80, jugador_real_id: 180 },
      { id: 1703, nombre: "Linke", posicion: "DFC", valoracion: 79, jugador_real_id: 181 },
      { id: 1704, nombre: "Anderson", posicion: "DFC", valoracion: 78, jugador_real_id: 182 },
      { id: 1705, nombre: "Lizarazu", posicion: "LI", valoracion: 84, jugador_real_id: 183 },
      { id: 1706, nombre: "Jeremies", posicion: "MCD", valoracion: 78, jugador_real_id: 184 },
      { id: 1707, nombre: "Hargreaves", posicion: "MC", valoracion: 76, jugador_real_id: 172 },
      { id: 1708, nombre: "Effenberg", posicion: "MC", valoracion: 85, jugador_real_id: 185 },
      { id: 1709, nombre: "Zickler", posicion: "ED", valoracion: 76, jugador_real_id: 186 },
      { id: 1710, nombre: "Elber", posicion: "DC", valoracion: 83, jugador_real_id: 187 },
      { id: 1711, nombre: "Jancker", posicion: "DC", valoracion: 76, jugador_real_id: 188 },
      { id: 1712, nombre: "Scholl", posicion: "SD", valoracion: 82, jugador_real_id: 189 },
      { id: 1713, nombre: "Sergio", posicion: "MCD", valoracion: 76, jugador_real_id: 190 },
      { id: 1714, nombre: "Pizarro", posicion: "DC", valoracion: 79, jugador_real_id: 191 },
      { id: 1715, nombre: "Fink", posicion: "MC", valoracion: 75, jugador_real_id: 192 }
    ]
  },
  {
    id: 18,
    nombre: "Milan 2003",
    liga: "Serie A",
    pais: "Italia",
    temporada: "2002/03",
    escudo: "🏆",
    media: 84,
    jugadores: [
      { id: 1801, nombre: "Dida", posicion: "POR", valoracion: 84, jugador_real_id: 31 },
      { id: 1802, nombre: "Cafu", posicion: "LD", valoracion: 85, jugador_real_id: 43 },
      { id: 1803, nombre: "Nesta", posicion: "DFC", valoracion: 88, jugador_real_id: 33 },
      { id: 1804, nombre: "Maldini", posicion: "DFC", valoracion: 88, jugador_real_id: 34 },
      { id: 1805, nombre: "Costacurta", posicion: "DFC", valoracion: 81, jugador_real_id: 193 },
      { id: 1806, nombre: "Gattuso", posicion: "MCD", valoracion: 81, jugador_real_id: 36 },
      { id: 1807, nombre: "Pirlo", posicion: "MCD", valoracion: 86, jugador_real_id: 37 },
      { id: 1808, nombre: "Seedorf", posicion: "MC", valoracion: 84, jugador_real_id: 38 },
      { id: 1809, nombre: "Rui Costa", posicion: "SD", valoracion: 86, jugador_real_id: 194 },
      { id: 1810, nombre: "Inzaghi", posicion: "DC", valoracion: 84, jugador_real_id: 40 },
      { id: 1811, nombre: "Shevchenko", posicion: "DC", valoracion: 91, jugador_real_id: 44 },
      { id: 1812, nombre: "Kaká", posicion: "MC", valoracion: 84, jugador_real_id: 39 },
      { id: 1813, nombre: "Ambrosini", posicion: "MC", valoracion: 77, jugador_real_id: 42 },
      { id: 1814, nombre: "Tomasson", posicion: "DC", valoracion: 78, jugador_real_id: 195 },
      { id: 1815, nombre: "Serginho", posicion: "LI", valoracion: 77, jugador_real_id: 196 }
    ]
  },
  {
    id: 19,
    nombre: "Liverpool 2005",
    liga: "Premier League",
    pais: "Inglaterra",
    temporada: "2004/05",
    escudo: "🏆",
    media: 81,
    jugadores: [
      { id: 1901, nombre: "Dudek", posicion: "POR", valoracion: 79, jugador_real_id: 197 },
      { id: 1902, nombre: "Finnan", posicion: "LD", valoracion: 76, jugador_real_id: 198 },
      { id: 1903, nombre: "Hyypiä", posicion: "DFC", valoracion: 80, jugador_real_id: 199 },
      { id: 1904, nombre: "Carragher", posicion: "DFC", valoracion: 82, jugador_real_id: 200 },
      { id: 1905, nombre: "Traore", posicion: "LI", valoracion: 73, jugador_real_id: 201 },
      { id: 1906, nombre: "Hamann", posicion: "MCD", valoracion: 81, jugador_real_id: 202 },
      { id: 1907, nombre: "Alonso", posicion: "MC", valoracion: 83, jugador_real_id: 90 },
      { id: 1908, nombre: "Gerrard", posicion: "MC", valoracion: 89, jugador_real_id: 203 },
      { id: 1909, nombre: "Riise", posicion: "EI", valoracion: 78, jugador_real_id: 204 },
      { id: 1910, nombre: "Baros", posicion: "DC", valoracion: 76, jugador_real_id: 205 },
      { id: 1911, nombre: "Cissé", posicion: "DC", valoracion: 77, jugador_real_id: 206 },
      { id: 1912, nombre: "Garcia", posicion: "SD", valoracion: 78, jugador_real_id: 207 },
      { id: 1913, nombre: "Kewell", posicion: "EI", valoracion: 79, jugador_real_id: 208 },
      { id: 1914, nombre: "Morientes", posicion: "DC", valoracion: 81, jugador_real_id: 11 },
      { id: 1915, nombre: "Biscan", posicion: "MCD", valoracion: 72, jugador_real_id: 209 }
    ]
  },
  {
    id: 20,
    nombre: "Chelsea 2021",
    liga: "Premier League",
    pais: "Inglaterra",
    temporada: "2020/21",
    escudo: "🏆",
    media: 84,
    jugadores: [
      { id: 2001, nombre: "Mendy", posicion: "POR", valoracion: 84, jugador_real_id: 210 },
      { id: 2002, nombre: "James", posicion: "LD", valoracion: 82, jugador_real_id: 211 },
      { id: 2003, nombre: "Christensen", posicion: "DFC", valoracion: 81, jugador_real_id: 212 },
      { id: 2004, nombre: "Thiago Silva", posicion: "DFC", valoracion: 87, jugador_real_id: 213 },
      { id: 2005, nombre: "Chilwell", posicion: "LI", valoracion: 81, jugador_real_id: 214 },
      { id: 2006, nombre: "Kante", posicion: "MCD", valoracion: 90, jugador_real_id: 215 },
      { id: 2007, nombre: "Jorginho", posicion: "MCD", valoracion: 83, jugador_real_id: 216 },
      { id: 2008, nombre: "Mount", posicion: "MC", valoracion: 83, jugador_real_id: 217 },
      { id: 2009, nombre: "Ziyech", posicion: "ED", valoracion: 81, jugador_real_id: 218 },
      { id: 2010, nombre: "Werner", posicion: "DC", valoracion: 82, jugador_real_id: 219 },
      { id: 2011, nombre: "Havertz", posicion: "MC", valoracion: 83, jugador_real_id: 220 },
      { id: 2012, nombre: "Pulisic", posicion: "EI", valoracion: 81, jugador_real_id: 221 },
      { id: 2013, nombre: "Alonso", posicion: "LI", valoracion: 78, jugador_real_id: 222 },
      { id: 2014, nombre: "Giroud", posicion: "DC", valoracion: 80, jugador_real_id: 223 },
      { id: 2015, nombre: "Rudiger", posicion: "DFC", valoracion: 82, jugador_real_id: 224 }
    ]
  },
  {
    id: 21,
    nombre: "Bayern Munich 2020",
    liga: "Bundesliga",
    pais: "Alemania",
    temporada: "2019/20",
    escudo: "🏆",
    media: 87,
    jugadores: [
      { id: 2101, nombre: "Neuer", posicion: "POR", valoracion: 90, jugador_real_id: 61 },
      { id: 2102, nombre: "Kimmich", posicion: "LD", valoracion: 88, jugador_real_id: 225 },
      { id: 2103, nombre: "Boateng", posicion: "DFC", valoracion: 83, jugador_real_id: 63 },
      { id: 2104, nombre: "Alaba", posicion: "DFC", valoracion: 86, jugador_real_id: 65 },
      { id: 2105, nombre: "Davies", posicion: "LI", valoracion: 84, jugador_real_id: 226 },
      { id: 2106, nombre: "Goretzka", posicion: "MCD", valoracion: 85, jugador_real_id: 227 },
      { id: 2107, nombre: "Thiago", posicion: "MC", valoracion: 88, jugador_real_id: 228 },
      { id: 2108, nombre: "Müller", posicion: "MC", valoracion: 87, jugador_real_id: 68 },
      { id: 2109, nombre: "Gnabry", posicion: "ED", valoracion: 85, jugador_real_id: 229 },
      { id: 2110, nombre: "Lewandowski", posicion: "DC", valoracion: 92, jugador_real_id: 230 },
      { id: 2111, nombre: "Coman", posicion: "EI", valoracion: 84, jugador_real_id: 231 },
      { id: 2112, nombre: "Perisic", posicion: "EI", valoracion: 81, jugador_real_id: 232 },
      { id: 2113, nombre: "Martinez", posicion: "MCD", valoracion: 81, jugador_real_id: 67 },
      { id: 2114, nombre: "Cuisance", posicion: "MC", valoracion: 74, jugador_real_id: 233 },
      { id: 2115, nombre: "Tolisso", posicion: "MC", valoracion: 81, jugador_real_id: 234 }
    ]
  },
  {
    id: 22,
    nombre: "Real Madrid 2022",
    liga: "La Liga",
    pais: "España",
    temporada: "2021/22",
    escudo: "🏆",
    media: 87,
    jugadores: [
      { id: 2201, nombre: "Courtois", posicion: "POR", valoracion: 90, jugador_real_id: 235 },
      { id: 2202, nombre: "Carvajal", posicion: "LD", valoracion: 83, jugador_real_id: 80 },
      { id: 2203, nombre: "Militao", posicion: "DFC", valoracion: 85, jugador_real_id: 236 },
      { id: 2204, nombre: "Alaba", posicion: "DFC", valoracion: 87, jugador_real_id: 65 },
      { id: 2205, nombre: "Mendy", posicion: "LI", valoracion: 83, jugador_real_id: 237 },
      { id: 2206, nombre: "Casemiro", posicion: "MCD", valoracion: 89, jugador_real_id: 95 },
      { id: 2207, nombre: "Modric", posicion: "MC", valoracion: 91, jugador_real_id: 85 },
      { id: 2208, nombre: "Kroos", posicion: "MC", valoracion: 88, jugador_real_id: 74 },
      { id: 2209, nombre: "Valverde", posicion: "MC", valoracion: 84, jugador_real_id: 238 },
      { id: 2210, nombre: "Benzema", posicion: "DC", valoracion: 91, jugador_real_id: 88 },
      { id: 2211, nombre: "Vinicius", posicion: "EI", valoracion: 86, jugador_real_id: 239 },
      { id: 2212, nombre: "Asensio", posicion: "ED", valoracion: 81, jugador_real_id: 96 },
      { id: 2213, nombre: "Rodrygo", posicion: "ED", valoracion: 81, jugador_real_id: 240 },
      { id: 2214, nombre: "Camavinga", posicion: "MC", valoracion: 80, jugador_real_id: 241 },
      { id: 2215, nombre: "Ceballos", posicion: "MC", valoracion: 78, jugador_real_id: 242 }
    ]
  },
  {
    id: 23,
    nombre: "Real Madrid 2024",
    liga: "La Liga",
    pais: "España",
    temporada: "2023/24",
    escudo: "🏆",
    media: 88,
    jugadores: [
      { id: 2301, nombre: "Courtois", posicion: "POR", valoracion: 90, jugador_real_id: 235 },
      { id: 2302, nombre: "Carvajal", posicion: "LD", valoracion: 85, jugador_real_id: 80 },
      { id: 2303, nombre: "Militao", posicion: "DFC", valoracion: 86, jugador_real_id: 236 },
      { id: 2304, nombre: "Alaba", posicion: "DFC", valoracion: 85, jugador_real_id: 65 },
      { id: 2305, nombre: "Mendy", posicion: "LI", valoracion: 84, jugador_real_id: 237 },
      { id: 2306, nombre: "Valverde", posicion: "MC", valoracion: 87, jugador_real_id: 238 },
      { id: 2307, nombre: "Modric", posicion: "MC", valoracion: 88, jugador_real_id: 85 },
      { id: 2308, nombre: "Kroos", posicion: "MC", valoracion: 88, jugador_real_id: 74 },
      { id: 2309, nombre: "Bellingham", posicion: "MC", valoracion: 91, jugador_real_id: 243 },
      { id: 2310, nombre: "Benzema", posicion: "DC", valoracion: 88, jugador_real_id: 88 },
      { id: 2311, nombre: "Vinicius", posicion: "EI", valoracion: 90, jugador_real_id: 239 },
      { id: 2312, nombre: "Rodrygo", posicion: "ED", valoracion: 84, jugador_real_id: 240 },
      { id: 2313, nombre: "Camavinga", posicion: "MC", valoracion: 83, jugador_real_id: 241 },
      { id: 2314, nombre: "Tchouameni", posicion: "MCD", valoracion: 84, jugador_real_id: 244 },
      { id: 2315, nombre: "Joselu", posicion: "DC", valoracion: 78, jugador_real_id: 245 }
    ]
  },
  {
    id: 24,
    nombre: "Borussia Dortmund 1997",
    liga: "Bundesliga",
    pais: "Alemania",
    temporada: "1996/97",
    escudo: "🏆",
    media: 80,
    jugadores: [
      { id: 2401, nombre: "Klos", posicion: "POR", valoracion: 81, jugador_real_id: 246 },
      { id: 2402, nombre: "Reuter", posicion: "LD", valoracion: 78, jugador_real_id: 247 },
      { id: 2403, nombre: "Kohler", posicion: "DFC", valoracion: 82, jugador_real_id: 248 },
      { id: 2404, nombre: "Julio César", posicion: "DFC", valoracion: 78, jugador_real_id: 249 },
      { id: 2405, nombre: "Rowland", posicion: "LI", valoracion: 74, jugador_real_id: 250 },
      { id: 2406, nombre: "Sousa", posicion: "MCD", valoracion: 79, jugador_real_id: 251 },
      { id: 2407, nombre: "Möller", posicion: "SD", valoracion: 82, jugador_real_id: 252 },
      { id: 2408, nombre: "Freund", posicion: "MCD", valoracion: 77, jugador_real_id: 253 },
      { id: 2409, nombre: "Riedle", posicion: "DC", valoracion: 80, jugador_real_id: 254 },
      { id: 2410, nombre: "Herrlich", posicion: "DC", valoracion: 77, jugador_real_id: 255 },
      { id: 2411, nombre: "Zorc", posicion: "MC", valoracion: 78, jugador_real_id: 256 },
      { id: 2412, nombre: "Lambert", posicion: "DFC", valoracion: 76, jugador_real_id: 257 },
      { id: 2413, nombre: "Heinrich", posicion: "LI", valoracion: 74, jugador_real_id: 258 },
      { id: 2414, nombre: "Ricken", posicion: "MC", valoracion: 76, jugador_real_id: 259 },
      { id: 2415, nombre: "Chapuisat", posicion: "DC", valoracion: 81, jugador_real_id: 260 }
    ]
  },
  {
    id: 25,
    nombre: "Juventus 1996",
    liga: "Serie A",
    pais: "Italia",
    temporada: "1995/96",
    escudo: "🏆",
    media: 82,
    jugadores: [
      { id: 2501, nombre: "Peruzzi", posicion: "POR", valoracion: 83, jugador_real_id: 261 },
      { id: 2502, nombre: "Torricelli", posicion: "LD", valoracion: 77, jugador_real_id: 262 },
      { id: 2503, nombre: "Ferrara", posicion: "DFC", valoracion: 82, jugador_real_id: 263 },
      { id: 2504, nombre: "Montero", posicion: "DFC", valoracion: 81, jugador_real_id: 264 },
      { id: 2505, nombre: "Pessotto", posicion: "LI", valoracion: 76, jugador_real_id: 265 },
      { id: 2506, nombre: "Deschamps", posicion: "MCD", valoracion: 84, jugador_real_id: 266 },
      { id: 2507, nombre: "Jugovic", posicion: "MC", valoracion: 78, jugador_real_id: 267 },
      { id: 2508, nombre: "Conte", posicion: "MC", valoracion: 79, jugador_real_id: 268 },
      { id: 2509, nombre: "Del Piero", posicion: "SD", valoracion: 88, jugador_real_id: 269 },
      { id: 2510, nombre: "Ravanelli", posicion: "DC", valoracion: 82, jugador_real_id: 270 },
      { id: 2511, nombre: "Vialli", posicion: "DC", valoracion: 84, jugador_real_id: 271 },
      { id: 2512, nombre: "Boksic", posicion: "DC", valoracion: 81, jugador_real_id: 272 },
      { id: 2513, nombre: "Sousa", posicion: "MC", valoracion: 77, jugador_real_id: 251 },
      { id: 2514, nombre: "Padovano", posicion: "DC", valoracion: 75, jugador_real_id: 273 },
      { id: 2515, nombre: "Amoruso", posicion: "DFC", valoracion: 74, jugador_real_id: 274 }
    ]
  },
  {
    id: 26,
    nombre: "Real Madrid 1998",
    liga: "La Liga",
    pais: "España",
    temporada: "1997/98",
    escudo: "🏆",
    media: 83,
    jugadores: [
      { id: 2601, nombre: "Illgner", posicion: "POR", valoracion: 83, jugador_real_id: 275 },
      { id: 2602, nombre: "Sanchís", posicion: "DFC", valoracion: 80, jugador_real_id: 276 },
      { id: 2603, nombre: "Hierro", posicion: "DFC", valoracion: 86, jugador_real_id: 3 },
      { id: 2604, nombre: "Karembeu", posicion: "MC", valoracion: 79, jugador_real_id: 277 },
      { id: 2605, nombre: "Roberto Carlos", posicion: "LI", valoracion: 88, jugador_real_id: 5 },
      { id: 2606, nombre: "Redondo", posicion: "MCD", valoracion: 86, jugador_real_id: 278 },
      { id: 2607, nombre: "Seedorf", posicion: "SD", valoracion: 82, jugador_real_id: 38 },
      { id: 2608, nombre: "Mijatovic", posicion: "DC", valoracion: 81, jugador_real_id: 279 },
      { id: 2609, nombre: "Raúl", posicion: "DC", valoracion: 86, jugador_real_id: 12 },
      { id: 2610, nombre: "Morientes", posicion: "DC", valoracion: 80, jugador_real_id: 11 },
      { id: 2611, nombre: "Suker", posicion: "DC", valoracion: 83, jugador_real_id: 280 },
      { id: 2612, nombre: "Panucci", posicion: "LD", valoracion: 78, jugador_real_id: 281 },
      { id: 2613, nombre: "Amavisca", posicion: "ED", valoracion: 76, jugador_real_id: 282 },
      { id: 2614, nombre: "Zamorano", posicion: "DC", valoracion: 81, jugador_real_id: 283 },
      { id: 2615, nombre: "Secretario", posicion: "LD", valoracion: 72, jugador_real_id: 284 }
    ]
  },
  {
    id: 27,
    nombre: "Real Madrid 2000",
    liga: "La Liga",
    pais: "España",
    temporada: "1999/00",
    escudo: "🏆",
    media: 85,
    jugadores: [
      { id: 2701, nombre: "Casillas", posicion: "POR", valoracion: 80, jugador_real_id: 1 },
      { id: 2702, nombre: "Salgado", posicion: "LD", valoracion: 77, jugador_real_id: 2 },
      { id: 2703, nombre: "Hierro", posicion: "DFC", valoracion: 85, jugador_real_id: 3 },
      { id: 2704, nombre: "Helguera", posicion: "DFC", valoracion: 78, jugador_real_id: 4 },
      { id: 2705, nombre: "Roberto Carlos", posicion: "LI", valoracion: 89, jugador_real_id: 5 },
      { id: 2706, nombre: "Redondo", posicion: "MCD", valoracion: 85, jugador_real_id: 278 },
      { id: 2707, nombre: "Figo", posicion: "ED", valoracion: 89, jugador_real_id: 8 },
      { id: 2708, nombre: "Guti", posicion: "SD", valoracion: 79, jugador_real_id: 285 },
      { id: 2709, nombre: "Anelka", posicion: "DC", valoracion: 83, jugador_real_id: 286 },
      { id: 2710, nombre: "Raúl", posicion: "DC", valoracion: 88, jugador_real_id: 12 },
      { id: 2711, nombre: "Morientes", posicion: "DC", valoracion: 82, jugador_real_id: 11 },
      { id: 2712, nombre: "McManaman", posicion: "MC", valoracion: 79, jugador_real_id: 9 },
      { id: 2713, nombre: "Karembeu", posicion: "MC", valoracion: 78, jugador_real_id: 277 },
      { id: 2714, nombre: "Suker", posicion: "DC", valoracion: 80, jugador_real_id: 280 },
      { id: 2715, nombre: "Flavio Conceicao", posicion: "MC", valoracion: 75, jugador_real_id: 13 }
    ]
  },
  {
    id: 28,
    nombre: "Barcelona 2006",
    liga: "La Liga",
    pais: "España",
    temporada: "2005/06",
    escudo: "🏆",
    media: 84,
    jugadores: [
      { id: 2801, nombre: "Valdés", posicion: "POR", valoracion: 82, jugador_real_id: 16 },
      { id: 2802, nombre: "Belletti", posicion: "LD", valoracion: 76, jugador_real_id: 287 },
      { id: 2803, nombre: "Puyol", posicion: "DFC", valoracion: 86, jugador_real_id: 19 },
      { id: 2804, nombre: "Márquez", posicion: "DFC", valoracion: 81, jugador_real_id: 288 },
      { id: 2805, nombre: "Van Bronckhorst", posicion: "LI", valoracion: 79, jugador_real_id: 289 },
      { id: 2806, nombre: "Edmilson", posicion: "MCD", valoracion: 78, jugador_real_id: 290 },
      { id: 2807, nombre: "Xavi", posicion: "MC", valoracion: 87, jugador_real_id: 22 },
      { id: 2808, nombre: "Iniesta", posicion: "MC", valoracion: 83, jugador_real_id: 23 },
      { id: 2809, nombre: "Giuly", posicion: "ED", valoracion: 79, jugador_real_id: 291 },
      { id: 2810, nombre: "Eto'o", posicion: "DC", valoracion: 88, jugador_real_id: 26 },
      { id: 2811, nombre: "Ronaldinho", posicion: "EI", valoracion: 95, jugador_real_id: 292 },
      { id: 2812, nombre: "Deco", posicion: "MC", valoracion: 84, jugador_real_id: 121 },
      { id: 2813, nombre: "Larsson", posicion: "DC", valoracion: 80, jugador_real_id: 293 },
      { id: 2814, nombre: "Messi", posicion: "ED", valoracion: 81, jugador_real_id: 25 },
      { id: 2815, nombre: "Van Bommel", posicion: "MCD", valoracion: 81, jugador_real_id: 294 }
    ]
  }
]

export const posiciones = ['POR', 'DD', 'DC', 'LI', 'MCD', 'MC', 'MD', 'MI', 'ED', 'EI', 'SD']

export function getEquipoAleatorio() {
  return equipos[Math.floor(Math.random() * equipos.length)]
}

export function getJugadoresPorPosicion(equipo, posicion) {
  return equipo.jugadores.filter(j => j.posicion === posicion)
}

export const formaciones = {
  '4-3-3': {
    nombre: '4-3-3',
    posiciones: ['POR', 'LD', 'DFC', 'DFC', 'LI', 'MCD', 'MC', 'MC', 'ED', 'DC', 'EI']
  },
  '4-2-3-1': {
    nombre: '4-2-3-1',
    posiciones: ['POR', 'LD', 'DFC', 'DFC', 'LI', 'MCD', 'MCD', 'ED', 'MC', 'EI', 'DC']
  },
  '4-4-2': {
    nombre: '4-4-2',
    posiciones: ['POR', 'LD', 'DFC', 'DFC', 'LI', 'MD', 'MC', 'MC', 'MI', 'DC', 'DC']
  },
  '5-3-2': {
    nombre: '5-3-2',
    posiciones: ['POR', 'LD', 'DFC', 'DFC', 'DFC', 'LI', 'MCD', 'MC', 'MCD', 'DC', 'DC']
  }
}

export const compatibilidad = {
  'POR': ['POR'],
  'LD': ['LD'],
  'DFC': ['DFC'],
  'LI': ['LI'],
  'MCD': ['MCD', 'MC'],
  'MC':  ['MC', 'MCD', 'SD'],
  'MD':  ['MD', 'ED', 'SD'],
  'MI':  ['MI', 'EI', 'SD'],
  'ED':  ['ED', 'MD', 'SD'],
  'EI':  ['EI', 'MI', 'SD'],
  'DC':  ['DC', 'SD']
}

export function getJugadoresCompatibles(equipo, posicionRequerida) {
  const posicionesValidas = compatibilidad[posicionRequerida]
  return equipo.jugadores.filter(j => posicionesValidas.includes(j.posicion))
}